language: R
dist: bionic
sudo: false
cache: packages

r_packages:
  - devtools

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/netmhc2pan
  - richelbilderbeek/tmhmm
  - MangoTheCat/goodpractice
  - ropensci/spelling

before_script:
  - sudo apt-get update
  # Boost
  - sudo apt-get install libboost-all-dev
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev libqt5svg5*
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # Install and test TMHMM
  - Rscript -e "tmhmm::install_tmhmm()"
  - echo -e ">sp|L0T550|RIP2_MYCTU_158_180\nAVLWAGVAFLAFLQLTALVLNLL" > example.fasta
  - |
    ~/.local/share/tmhmm-2.0c/bin/decodeanhmm.Linux_x86_64 \
    ~/.local/share/tmhmm-2.0c/lib/TMHMM2.0.model \
    example.fasta \
    -f ~/.local/share/tmhmm-2.0c/lib/TMHMM2.0.options || true
  - rm example.fasta
  # Install and test NetMHC2pan
  - sudo apt install tcsh
  - Rscript -e "netmhc2pan::install_netmhc2pan()"
  - echo -e ">sp|L0T550|RIP2_MYCTU_158_180\nAVLWAGVAFLAFLQLTALVLNLL" > example.fasta
  - ~/.local/share/netMHCIIpan-3.2/netMHCIIpan -f example.fasta
  - rm example.fasta
  # Build and run C++ code of epitopeome
  - qmake
  - make --silent
  - ./epitopeome
  # proselint
  - sudo pip install proselint

after_success:
  - cat ~/epitopeome/inst/extdata/proteome.fasta || true
  - cat ~/inst/extdata/proteome.fasta || true
  - find . | egrep "fasta"
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'

after_failure:
  - pwd
  - cat ./epitopeome.Rcheck/00_pkg_src/epitopeome/inst/extdata/proteome.fasta || true
  - cat ./epitopeome.Rcheck/epitopeome/extdata/proteome.fasta || true
  - cat ./inst/extdata/proteome.fasta || true
  - find . | egrep "fasta"


