# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Creates an 'epitopeome' from a TMHMM and NetMHC2pan file
#' @param tmhs_filename file that contains the TMHs as created by TMHMM
#' @param netmhc2pan_filename file that contains the NetMHC2pan results
#' @return a map, with the sequence name as key, and its 'epitopeome'
#'   as value
#' @author Richel J.C. Bilderbeek
#' @export
create_epitopeome_cpp <- function(tmhs_filename, netmhc2pan_filename) {
    .Call(`_epitopeome_create_epitopeome_cpp`, tmhs_filename, netmhc2pan_filename)
}

#' Creates a FASTA file with only the TMHs
#' @param tmhs_filename file that contains the TMHs as created by TMHMM
#' @param netmhc2pan_filename file that contains the NetMHC2pan results
#' @param epitopeome_filename name of the create epitopeome file, 
#'   saved in FASTA format
#' @return nothing
#' @author Richel J.C. Bilderbeek
#' @export
create_epitopeome_file_cpp <- function(tmhs_filename, netmhc2pan_filename, epitopeome_filename) {
    invisible(.Call(`_epitopeome_create_epitopeome_file_cpp`, tmhs_filename, netmhc2pan_filename, epitopeome_filename))
}

#' Creates a FASTA file with only the TMHs for a TMHMM file
#' as created by a locally installled TMHMM binary
#' @param tmhs_filename file that contains the TMHs
#'   as created by a locally installed TMHMM binary
#' @return a dictionary with sequence names as key,
#'   and a 'locatome' as values.
#' @author Richel J.C. Bilderbeek
#' @export
create_locatome_cpp <- function(tmhs_filename) {
    .Call(`_epitopeome_create_locatome_cpp`, tmhs_filename)
}

#' Split a string
#' @param input the input string
#' @param seperator the seperator
#' @return a vector of strings
#' @author Richel J.C. Bilderbeek
split_str <- function(input, seperator) {
    .Call(`_epitopeome_split_str`, input, seperator)
}

