# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Creates a FASTA file with only the TMHs
#' @param tmhs_filename file that contains the TMHs as created by TMHMM
#' @param netmhc2pan_filename file that contains the NetMHC2pan results
#' @return nothing
#' @author Richel J.C. Bilderbeek
create_epitopeome_cpp <- function(tmhs_filename, netmhc2pan_filename) {
    .Call(`_epitopeome_create_epitopeome_cpp`, tmhs_filename, netmhc2pan_filename)
}

#' Creates a FASTA file with only the TMHs
#' @param tmhs_filename file that contains the TMHs as created by TMHMM
#' @return nothing
#' @author Richel J.C. Bilderbeek
create_locatome_cpp <- function(tmhs_filename) {
    .Call(`_epitopeome_create_locatome_cpp`, tmhs_filename)
}

#' Split a string
#' @param input the input string
#' @param seperator the seperator
#' @return a vector of strings
#' @author Richel J.C. Bilderbeek
split_str <- function(input, seperator) {
    .Call(`_epitopeome_split_str`, input, seperator)
}

